### ISSUE TITLE
Enable plugin depending on playlist

### ISSUE THREAD

**Issue by exKitsune** [JulienML/BetterChat#2]
Could we have a feature that could activate more aggressive filters or just block chat altogether in certain playlists like 1s?

I queue with my friends in 3s and 2s so we can mess with each other there, and we don't really care about what the other side says

But when it comes to 1s I'd rather block every message

**Comment by JulienML** [comment]
Thank you for your suggestion. I didn't think about the need to have a different configuration for each playlist, I will try to add this option in the next major update :)

**Comment by JulienML** [comment]
It took me a while to implement your idea, but it will be available in [v3.0.0](https://github.com/JulienML/BetterChat/releases/tag/v3.0.0).
I close this issue :)
