### ISSUE TITLE
Crashing to desktop

### ISSUE THREAD

**Issue by astreimb** [JulienML/BetterChat#3]
Crashes for me and a mate, possibly related to using ballchaser replay uploads plugin? It crashes usually at the end of/in between rounds, while in a private server is the most common situation, frequent crashing.

```
Crash to desktop [12783.28] Vanity: All Vanity Queries Complete
[12783.37] Log: FSaveDataExportTask(0) wrote 5916454 bytes to memory
[12783.37] Log: SaveGameDataAsync game thread time: 64 ms
[12783.44] Log: Deleting old save file ..\..\TAGame\SaveData\DBE_Production\76561197963334451.save
[12783.44] Log: SaveDataExport(0): Finished - File:[..\..\TAGame\SaveData\DBE_Production\76561197963334451_2.save] Result:[1]
[12807.56] Log: === Critical error: ===
Fatal error!

Address = 0x6a3539aa (filename not found) [in C:\Users\Player 2\AppData\Roaming\bakkesmod\bakkesmod\dll\pluginsdk.dll]
Address = 0x67edd82b (filename not found) [in C:\Users\Player 2\AppData\Roaming\bakkesmod\bakkesmod\plugins\betterchat.dll]
Address = 0x6a358a56 (filename not found) [in C:\Users\Player 2\AppData\Roaming\bakkesmod\bakkesmod\dll\pluginsdk.dll]
Address = 0x6a35743c (filename not found) [in C:\Users\Player 2\AppData\Roaming\bakkesmod\bakkesmod\dll\pluginsdk.dll]
Address = 0x6a35b95a (filename not found) [in C:\Users\Player 2\AppData\Roaming\bakkesmod\bakkesmod\dll\pluginsdk.dll]
Address = 0x6a35a4f8 (filename not found) [in C:\Users\Player 2\AppData\Roaming\bakkesmod\bakkesmod\dll\pluginsdk.dll]
Address = 0x6f747fde (filename not found) [in C:\Users\Player 2\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0x6f747e36 (filename not found) [in C:\Users\Player 2\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0xd8e1d8a  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0x6f747d90 (filename not found) [in C:\Users\Player 2\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0xd8e6b70  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0x6f747e9a (filename not found) [in C:\Users\Player 2\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0xd8e6971  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0x6f747c59 (filename not found) [in C:\Users\Player 2\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0xdb2955a  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xd8e5213  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xddda741  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xd8d8bbd  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xd8e6b70  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0x6f747e9a (filename not found) [in C:\Users\Player 2\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0xd8e1d8a  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0x6f747d90 (filename not found) [in C:\Users\Player 2\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0xd8e6b70  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0x6f747e9a (filename not found) [in C:\Users\Player 2\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0xd8e1d8a  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0x6f747d90 (filename not found) [in C:\Users\Player 2\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0xd8e6b70  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0x6f747e9a (filename not found) [in C:\Users\Player 2\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0xd8e6971  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0x6f747c59 (filename not found) [in C:\Users\Player 2\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0xdb2955a  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xe0f5b3a  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xe0f989e  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xe0f9665  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xe0f909e  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xe0f9831  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xe0f979f  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xe161211  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xe18d376  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xdcb8047  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xdc5411f  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xe389555  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xe316b2d  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xe3120fc  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xe31214a  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xe318541  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xeb9ee36  (filename not found) [in K:\SteamLibrary\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xfd537344 (filename not found) [in C:\WINDOWS\System32\KERNEL32.DLL]
Address = 0xfece26b1 (filename not found) [in C:\WINDOWS\SYSTEM32\ntdll.dll]
Address = 0xfece26b1 (filename not found) [in C:\WINDOWS\SYSTEM32\ntdll.dll]
```

**Comment by JulienML** [comment]
Thank you for reporting this problem. I wasn't aware of this issue, I'll look into it. I'll get back to you if I have an idea :)

**Comment by JulienML** [comment]
I am still investigating this bug but I have a few questions that could help me:
- Is it crashing when you disable the auto upload (and let BetterChat enabled)?
- Is it crashing when you disable BetterChat (and let the auto upload enabled)?
- If it is still crashing, does it crash when you disable both?
- Did you provide the entire log file? If not, can you provide it?

**Comment by ynworth** [comment]
My game crashes specifically when I quickchat, both with or without anti spam enabled, stopped using it after that

**Comment by JulienML** [comment]
In order to understand what is the problem, can you provide the rocket league log file (Documents\My Games\Rocket League\TAGame\Logs\Launch.log) and the bakkesmod log file (C:\Users\\[your username]\AppData\Roaming\bakkesmod\bakkesmod\bakkesmod.log)?
Thank you

**Comment by astreimb** [comment]
> In order to understand what is the problem, can you provide the rocket league log file (Documents\My Games\Rocket League\TAGame\Logs\Launch.log) and the bakkesmod log file (C:\Users\[your username]\AppData\Roaming\bakkesmod\bakkesmod\bakkesmod.log)? Thank you

[bakkesmod.log](https://github.com/user-attachments/files/17498338/bakkesmod.log)
[Launch.log](https://github.com/user-attachments/files/17498339/Launch.log)

**Comment by JulienML** [comment]
I'm still looking for a solution to your problem, could you please provide me with the .dmp file found here: Documents\My Games\Rocket League\TAGame\Logs\
Thank you

**Comment by Yanickdk** [comment]
Hey, I'm encountering a somewhat same problem, When I type in the chat (this is important) in a party, Everyones game with the plugin crashes, Me and my friend have disabled the plugin for now and seems to work (Ill open a issue for better communication)

**Comment by astreimb** [comment]
> I'm still looking for a solution to your problem, could you please provide me with the .dmp file found here: Documents\My Games\Rocket League\TAGame\Logs Thank you

[-v241014.43841.462850-2024.10.30-11.22.09.dmp](https://github.com/user-attachments/files/17612477/-v241014.43841.462850-2024.10.30-11.22.09.dmp)
[-v241014.43841.462850-2024.10.31-14.34.58.dmp](https://github.com/user-attachments/files/17612479/-v241014.43841.462850-2024.10.31-14.34.58.dmp)


To add to this, I have a secondary issue where I can't uninstall this plugin. A surgical removal did nothing, it comes back somehow

**Comment by astreimb** [comment]
Can confirm private games make me crash constantly, even when not in party, with all chat disabled, and this plugin also disabled
Going to see if it's because someone used the chat, or if just being in the lobby causes it. I update sometime later

**Comment by astreimb** [comment]
Can confirm that crashing occurs only when spectating, either as a spectator, or in the stats-screen before you choose a team. Hence only crashing in private games. Chats have nothing to do with it I think, and I can't tell if this plugin is causing any of this other than the early mention of it as it logs the crash event. Here's a fresh log:

[Launch.log](https://github.com/user-attachments/files/17837741/Launch.log)

**Comment by JulienML** [comment]
Thanks for the clarification, I now understand why the plugin crashes: at the start of the game, the plugin tries to get your car's information and of course this doesn't work if you're spectating. I'll fix that in the next update.
Is this the only situation where the game crashes for you?

**Comment by astreimb** [comment]
> Thanks for the clarification, I now understand why the plugin crashes: at the start of the game, the plugin tries to get your car's information and of course this doesn't work if you're spectating. I'll fix that in the next update. Is this the only situation where the game crashes for you?

As far as my memory is to believe, it is
