### ISSUE TITLE
TimeStamp Issue

### ISSUE THREAD

**Issue by SN4K-OFF** [JulienML/BetterChat#4]
Hello,

Je vois les timestamps quand un message est effacé, le contenu du message est vide mais je vois le timestamp, j'ai la dernière version du plugin et la dernière version de bakkesmod

**Comment by JulienML** [comment]
Salut, dans la dernière version du plugin les timestamps sont bien supprimés, c'est juste qu'il faut attendre que les équipes de Bakkesmod mettent à jour le plugin dans leur mod. Une fois qu'ils l'auront fait, tu auras juste à mettre à jour Bakkesmod et ça marchera 👍

**Comment by SN4K-OFF** [comment]
Yes, j'ai ajouté le plugin via bakkesmod, du coup j'ai compilé la version github et ça fonctionne bien

**Comment by JulienML** [comment]
Parfait alors
